-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
    -   id: flake8
    -   id: trailing-whitespace
